apiVersion: v1
kind: ConfigMap
metadata:
  name: gitlab-runner-docker
data:
  config.toml: |
    concurrent = 4
    check_interval = 1

    [[runners]]
      name = "gitlab-docker-runner"
      url = "http://$HOST/ci"
      token = "$TOKEN"
      executor = "kubernetes"
      [runners.kubernetes]
        namespace = "gitlab"
        image = "busybox"
    #   [runners.docker]
    #     tls_verify = false
    #     image = "python:3.5"
    #     privileged = true
    #     disable_cache = false
    #     volumes = ["/cache"]
    #   [runners.cache]
    #     Type = "s3"
    #     ServerAddress = "http://minio.gitlab/"
    #     AccessKey = ""
    #     SecretKey = ""
    #     BucketName = "runner"
