apiVersion: v1
kind: ConfigMap
metadata:
  name: $APP
data:
  config.toml: |
    concurrent = 4

    [[runners]]
      name = "Kubernetes Runner"
      url = "https://gitlab.com/ci"
      token = "$GITLAB_TOKEN"
      executor = "kubernetes"
      [runners.kubernetes]
        namespace = "$NS"
        image = "busybox"