apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: $APP
spec:
  replicas: $REPLICAS
  selector:
    matchLabels:
      name: $APP
  template:
    metadata:
      labels:
        name: $APP
    spec:
      containers:
      - args:
        - run
        image: gitlab/gitlab-runner:latest
        imagePullPolicy: Always
        name: $APP
        volumeMounts:
        - mountPath: /etc/gitlab-runner
          name: config
        - mountPath: /etc/ssl/certs
          name: cacerts
          readOnly: true
      restartPolicy: Always
      volumes:
      - configMap:
          name: $APP
        name: config
      - hostPath:
          path: /usr/share/ca-certificates/mozilla
        name: cacerts